### ISSUE TITLE
Do not display number of communities while still running

### ISSUE THREAD

**Issue by MarleneID** [rwth-acis/REST-OCD-Services#27]
When an algorithm is running the number of communities is displayed on the page of the cover which is really odd. The number of  communities is set to the number of nodes in the graph. This makes the impression that the algorithm has finished and it puts all nodes in their own community. It might be better to show something like "in progress" or "running " instead of a number because technically no communities have been found yet.

**Comment by MarleneID** [comment]
This might actually be an issue for the web client

**Comment by MaxKissgen** [comment]
It actually is an issue for the web client. I am **closing** this here and would ask you to re-open it there
