### ISSUE TITLE
Adding images for wiki.

### ISSUE THREAD

**Issue by minemeraj** [rwth-acis/REST-OCD-Services#4]
![nodecontent1](https://cloud.githubusercontent.com/assets/2042835/13847953/021d59f4-ec50-11e5-9681-bed4d36f3189.png)
![nodecontent2](https://cloud.githubusercontent.com/assets/2042835/13847954/0237fafc-ec50-11e5-8c07-7d83c74ad5ba.png)
![xml1](https://cloud.githubusercontent.com/assets/2042835/13847956/024a77fe-ec50-11e5-99cd-9e0542efe497.png)
![xml2](https://cloud.githubusercontent.com/assets/2042835/13847955/0249cb24-ec50-11e5-81f1-a2b6ffd09313.png)

It's not an issue, it's just containing the images which will used in wiki page. As there is no way to upload images in the wiki, the image link of this issue would be used in the wiki.

**Comment by minemeraj** [comment]
![saml](https://cloud.githubusercontent.com/assets/2042835/13848636/f97f8ae4-ec52-11e5-82af-51ddc97cdeda.png)

**Comment by minemeraj** [comment]
![parameters](https://cloud.githubusercontent.com/assets/2042835/14109783/0040a5fa-f5c4-11e5-9d12-04f28021f743.png)

**Comment by minemeraj** [comment]
![algo1](https://cloud.githubusercontent.com/assets/2042835/14110285/12d755cc-f5c6-11e5-9fa1-bb7216272376.png)
![algo2](https://cloud.githubusercontent.com/assets/2042835/14110286/13edf29a-f5c6-11e5-824a-3d81dedbd841.png)

**Comment by MaxKissgen** [comment]
Closing this since we have an own website now and the wiki has since gotten the ability to include images
