### ISSUE TITLE
No visualization for a circular graph

### ISSUE THREAD

**Issue by schiemon** [rwth-acis/REST-OCD-Services#70]
On the graph page, the visualization stays blank for the following graph data:

```
0 1
1 0
```

Surprisingly, adding a node to it brings it back to life:

```
0 1
1 0
2 3
```

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/56340221/162957475-0cf80da8-7134-4903-8e85-213c0ac7669b.png">

**Comment by MaxKissgen** [comment]
What we could gather so far, the problem arises only if:

1. The graph is circular
2. The edges all have the same weights
3. The edges also have to describe a circular path, e.g. directed 
0 1
1 2
0 2 
does not produce the problem but undirected does

**Comment by MaxKissgen** [comment]
We have pinned down the problem. It happens when both the minimum weighted and maximum weighted average degrees are the same. In this case Our Layouthandler divides by zero at one point to determine node size, leaving the size to be NaN
