### ISSUE TITLE
where are the jars in lib?

### ISSUE THREAD

**Issue by sunnylian** [rwth-acis/REST-OCD-Services#8]
![image](https://user-images.githubusercontent.com/32296773/37270599-5b4f09dc-260a-11e8-9979-e098e015468d.png)

**Comment by rNzqe** [comment]
Did you run get_deps from ocd_build.xml?

**Comment by MaxKissgen** [comment]
Closing this since no answer was received and the service has since changed enough for this problem to likely become deprecated

**Comment by sunnylian** [comment]
您好，您的邮件我已收到，谢谢！
